Code review. Drop unused functions/methods/classes, arrange Trace () methods more effectively. Add class "ActionEvent" to encapsulate wxCommandEvent and to reduce code creating miscellaneous events.
Added new files:

* src/action_event.(hpp|cpp):
  added class ActionEvent encapsulating wxCommandEvent.
* src/merge_data.hpp

* src/Makefile.am
  (rapidsvn_RESOURCES): added "action_event.cpp"

* rapisvn.dsp
  files added to project:
  "action_event.hpp", "action_event.cpp"

* src/ids.hpp
  TOKEN_ERROR: new ID added

* src/action.hpp
  (global): updated forward declarations
  (Action::PostEvent):
  (Action::PostStringEvent):
  (Action::PostDataEvent):
	dropped unused methods

* src/rapidsvn_frame.hpp
  (RapidSvnFrame): added new method "TraceError"

* src/rapidsvn_frame.cpp
  (RapidSvnFrame::OnActionEvent): added handler for "TOKEN_ERROR" event;
   tracing error messages with special function - TraceError ()
  (RapidSvnFrame::TraceError): added function to display error messages
   in red font color

* src/simple_worker.(hpp|cpp)
  (SimpleWorker::PostStringEvent):
  (SimpleWorker::PostDataEvent):
    dropped unused functions
  (SimpleWorker::Trace): replaced with TraceError()

* src/simple_worker.cpp
  (SimpleWorker::Trace): replaced with SimpleWorker::TraceError()
  (SimpleWorker::Perform): replaced all Trace() calls with TraceError(), because
   they contain error messages to pass

* src/threaded_worker.(hpp|cpp)
  (ThreadedWorker::PostStringEvent):
  (ThreadedWorker::PostDataEvent):
  (ThreadedWorker::Trace):
    dropped unused functions

* src/threaded_worker.cpp
  (ThreadedWorker::Data::Trace): replaced with ThreadedWorker::Data::TraceError()
  (ThreadedWorker::Perform): replaced all Trace() calls with TraceError(), because
   they contain error messages to pass

* src/checkout_action.cpp
* src/diff_action.cpp
* src/external_program_action.cpp
* src/filelist_ctrl.cpp
* src/log_dlg.cpp
* src/simple_worker.cpp
* src/threaded_worker.cpp
* src/view_action.cpp

  (#include): "action_event.hpp" added

  (CheckoutAction::Perform):
  (DiffAction::Data::diffTarget):
  (ExternalProgramAction::Perform):
  (FileListCtrl::OnColumnLeftClick):
  (LogDlg::Data::OnGet):
  (LogDlg::Data::OnView):
  (LogDlg::Data::OnDiff):
  (LogDlg::Data::OnMerge):
  (LogDlg::Data::OnGet):
  (ThreadedWorker::Data::DeleteAction):
  (ThreadedWorker::Data::ExecuteAction):
  (ThreadedWorker::Data::DeleteAction):
  (SimpleWorker::Perform):
  (ViewAction::Perform):
	use new ActionEvent class instead of wxCommandEvent, PostStringEvent()
	or PostDataEvent()

* src/tracer.hpp
  (global): updated forward declarations
  (Tracer): added to base class function TraceError () for error messages tracing
  (EventTracer): added function TraceError ()
  (TextCtrlTracer): dropped unused class
  (ErrorTracer): dropped unused class

* src/tracer.cpp
  (#include): added "action_event.hpp", dropped "repodt_dlg.hpp" and "utils.hpp"
  (TextCtrlTracer): dropped unused class
  (ErrorTracer): dropped unused class
  (EventTracer::Trace, EventTracer::TraceError): use new ActionEvent class instead
    of wxCommandEvent

* src/utils.(hpp|cpp)
  (CreateActionEvent): deleted function not being used anymore

* src/listener.hpp
  (Listener::TraceError): unused function dropped

* src/listener.cpp
  (#include): "action_event.hpp" added
  (Listener::TraceError): unused function dropped
  (Listener::contextNotify): passes messages to Trace () function
   instead of creating an event for RapidSvnFrame on its own. Function
   Trace() knows exactly what to do.

* src/action.cpp

  (Action::PostEvent):
  (Action::PostStringEvent):
  (Action::PostDataEvent):
	deleted unused functions

  (Action::TraceError): call specific for error tracing function of Tracer
    instead of using usual Trace ()

Refactoring MergeAction so that it looks like other actions

* src/merge_data.hpp
  file added

* src/merge_dlg.hpp
  (#include): "merge_data.hpp" added
  (MergeData): structure moved to separate file "merge_data.hpp"
  (MergeDlg): dropped variable m_calledByLogDlg

* src/merge_dlg.cpp
  (MergeData::MergeData): deleted constructor, moved to "merge_data.hpp"
  (MergeDlg::MergeDlg): define m_data.calledByLogDlg instead of initializing
    m_calledByLogDlg
  (MergeDlg::InitializeData): moved m_calledByLogDlg to m_data;
    so replaced m_calledByLogDlg with m_data.calledByLogDlg

* src/merge_action.hpp

  (#include): replaced "merge_dlg.hpp" with "merge_data.hpp"
  (MergeAction): moved m_calledByLogDlg to MergeAction::m_data;

* src/merge_action.cpp

  (#include): deleted "merge_dlg.hpp"
  (MergeAction::MergeAction): define m_data.calledByLogDlg instead of initializing
    m_calledByLogDlg
  (MergeAction::MergeAction, MergeAction::Prepare): moved m_calledByLogDlg to m_data;
    so replacing m_calledByLogDlg with m_data.calledByLogDlg


* src/external_program_action.hpp
  (ExternalProgramAction): "protected" keyword replaced with "private", as nobody has
   an intentions to inherit from this class

git-svn-id: http://rapidsvn.tigris.org/svn/rapidsvn/trunk@7413 65390229-12b7-0310-b90b-f21a5aa7ec8e